# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  run_jekyll:
    desc: Run Jekyll server locally
    cmds:
      - bundle exec jekyll serve
    silent: true
